### ISSUE TITLE
关于部署的一点疑问

### ISSUE THREAD

**Issue by liuyang-70d12d** [aws-samples/amazon-ecr-replication-for-pub-container-images#1]
我按照 [在 AWS 中国区方便安全的使用海外公开容器镜像](https://aws.amazon.com/cn/blogs/china/convenient-and-safe-use-of-overseas-public-container-images-in-aws-china/)进行部署，发现 CloudFormation、CodeCommit都部署在了国内的账户上，相应的，CodeBuild也是在国内账户上完成。

随后拉取镜像失败，报错信息如下：

Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

我认为这个错误是由于在国内进行CodeBuild所导致的。

请问是上面的Blog文章哪里出了问题，还是我理解有误？毕竟现在的部署方式与图示也不相符（按图所示，CodeCommit与CodeBuild应该在海外IAM上完成吧）。

非常感谢您的杰出工作，也期待您的回复，谢谢！

**Comment by walkley** [comment]
@liuyang-70d12d 感谢您对本项目的关注。

本项目和相应博客描述的方案，是将CodeCommit、CodeBuild均部署在AWS海外区域，CodeBuild会将需要的容器镜像推送到AWS中国区ECR镜像仓库内。因此您在第一步配置CDK开发环境时，使用的AWS credential以及region等配置都是AWS海外区域，而在第四步运行cdk deploy命令时使用的AWS credential(Access Key, Secret Key)是AWS中国区的参数，这里参数的作用是用作海外CodeBuild推送镜像给国内ECR时赋予其访问国内AWS区域的权限。

希望上述描述能解答您的疑惑，如有不清楚的地方，欢迎您继续提出。

**Comment by liuyang-70d12d** [comment]
@walkley 
您好！
非常感谢您的回复，在您的指导下顺利完成了项目的部署。
谢谢您！
